from django.db import models

class List(models.Model):
	system = models.CharField(max_length=100)
	claim_id = models.BigIntegerField()
	ins = models.CharField(max_length=100)
	patient = models.CharField(max_length=100)
	charge = models.CharField(max_length=100)
	dos_from = models.CharField(max_length=100)
	dos_to = models.CharField(max_length=100)
	sent = models.CharField(max_length=100)
	fu_date = models.CharField(max_length=100)
	level_of_care = models.CharField(max_length=100)
	status = models.CharField(max_length=100)
	facility = models.CharField(max_length=100)
	worked_date = models.CharField(max_length=100)
	worked_rep = models.CharField(max_length=100)
	notes = models.TextField()
	completed = models.CharField(max_length=100)
	claim = models.CharField(max_length=100)
	allowed = models.CharField(max_length=100)
	paid = models.CharField(max_length=100)
	interest = models.CharField(max_length=100)
	coinsurance = models.CharField(max_length=100)
	copay = models.CharField(max_length=100)
	deductible = models.CharField(max_length=100)
	date_paid = models.CharField(max_length=100)
	cashed_date = models.CharField(max_length=100)
	payer = models.CharField(max_length=100)
	method = models.CharField(max_length=100)
	payment = models.CharField(max_length=100)
	bulk_amount = models.CharField(max_length=100)
	unique_id = models.CharField(max_length=100)
	emp_id = models.IntegerField()
	created_date = models.CharField(max_length=100)

	# def __str__(self):
	# 	return self.patient
