# Generated by Django 3.1.1 on 2020-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
