# Generated by Django 3.1.1 on 2020-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
